VPATH        += $(SRC)/Chemistry/simple_cool
INCLUDE_DIRS += -I$(SRC)/Chemistry/simple_cool
INCLUDE_DIRS += -I$(SRC)/Chombo
INCLUDE_DIRS += -I$(SRC)

CHEM_OBJ     += SimpleCool.o 
OBJ          += $(CHEM_OBJ)
CHEM_HEADERS += SimpleCool.H

HEADERS      += $(CHEM_HEADERS)

$(CHEM_OBJ):  $(HEADERS)

